services:

  caddy:
    build:
      context: ./caddy
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/www:/usr/share/caddy:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
